### PR TITLE
Revert "Substitute overrideFile to Override flag"

### PR DESCRIPTION
**Pull request by MohammadHadiAlizadeh**
Reverts OpenModelica/OMOctave#2

### CODE REVIEW

**Comment by arun3688** [comment]
@MohammadHadiAlizadeh I guess the long commandLine problems exists only on matlab, other packages OMPython and OMJulia may not have this problem so you don't need to change those things until it is necessary

**Comment by MohammadHadiAlizadeh** [comment]
@arun3688  
Unfortunately this problem exists in OMOctave as same as the OMMatlab.

It returns "the command line is too long" error

**Comment by MohammadHadiAlizadeh** [comment]
I resolved this problem in OMOctave with almost less effort and a little bit change based on the solution provided by you for OMMatlab

**Comment by arun3688** [comment]
> @arun3688 Unfortunately this problem exists in OMOctave as same as the OMMatlab.
> 
> It returns "the command line is too long" error

Yes Octave is almost simulate to matlab, But i am saying about other packages OMPython and OMJulia

**Pull request closed without merging**
